# Generated by Django 4.1.5 on 2023-03-30 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='member')),
            ],
        ),
    ]
