# Generated by Django 4.1.5 on 2023-03-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'More', 'verbose_name_plural': 'More'},
        ),
    ]
