# Generated by Django 4.1.5 on 2023-03-31 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_importmaterial_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_alter_client_options_alter_client_address_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(choices=[('Viettel', 'Viettel'), ('ghn', 'Giao hàng nhanh'), ('ghtk', 'Giao hàng tiết kiệm'), ('hbfoods', 'HBfoods'), ('other', 'Khác')], max_length=50, verbose_name='Đơn vị giao hàng')),
                ('cost', models.FloatField(default=0, verbose_name='Chi phí')),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'Mua hàng', 'verbose_name_plural': 'Mua hàng'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Giảm giá'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Có giảm giá'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='total_items',
            field=models.IntegerField(default=0, verbose_name='Tổng giá'),
        ),
    ]
