# Generated by Django 4.1.5 on 2023-03-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_material_loss_materialloss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importmaterial',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='importmaterial',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='materialloss',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='materialloss',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
